version: '3.3'

services:
  mmocr:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: mmorc:latest
    container_name: mmocr
    volumes:
      - 'mmocr-data:/mmocr'

volumes:
  mmocr-data: